# Generated by Django 4.1.5 on 2023-02-04 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_requested",
                    models.DateTimeField(blank=True, default=datetime.datetime.today),
                ),
                ("employee_name", models.TextField()),
                ("is_sick", models.BooleanField()),
                ("is_personal", models.BooleanField()),
                ("is_paid", models.BooleanField()),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_by", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
