# Generated by Django 4.1.5 on 2023-02-04 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_leaverequest_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="date_requested",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
