# Generated by Django 4.1.5 on 2023-02-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expensetracker",
            old_name="date",
            new_name="date_tr",
        ),
    ]
